# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  version "3.1.1"

  on_macos do
    on_arm do
      sha256 "ac9ced660a9443c734af9d4edc1b27723ae73b79f7d089f60e2cbf6db3492c09"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "de457b1536666e00f420b16688f3145f044b677c5190fa6f02cc09d3d6af628b"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d6566a3b0ef57edaa7e0eca45818f7cc63bc8d09026ca51dbafdea82d5a1ce1"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "16de3014c1e0e92db7089cc9a8d4c8cd17642e91ff11e9f26788161c2be4b98e"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_x86_64.tar.gz"
    end
  end

  name "gossm"
  desc "Interactive CLI for AWS SSM Session Manager"
  homepage "https://github.com/ottramst/gossm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gossm"]
    end
  end

  # No zap stanza required
end
