# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  version "3.0.0"

  on_macos do
    on_arm do
      sha256 "1ff6df5fd17702ed07c67f93ac9ee70ab74e0f8cbb6f654b50b71ada562236ba"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f32793ffaf75a36011b8fb6eb8043277e89001e1e5cc24a4a830d72971e2b9c"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd79a983fe847baa2bb808ec9d1cf0e83f844075e561cdfa5d983c8b9fb9365c"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29f5866784aeff1fc441db22100386c75a9c656e02b6299eacd4c441a62377aa"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_x86_64.tar.gz"
    end
  end

  name "gossm"
  desc "Interactive CLI for AWS SSM Session Manager"
  homepage "https://github.com/ottramst/gossm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gossm"]
    end
  end

  # No zap stanza required
end
