# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  version "3.2.0"

  on_macos do
    on_arm do
      sha256 "a4f97b595c460f8317e18fd6ac745b0f03a884246d88a1e2078066963eb59686"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b0573333329236e1c492eceecdbf9a08fcd7fa792380d1e92d39a8e49632954"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3cdc9f26ff1052ff6e4f6783768975b10a0c696431dd6abd4033fe256339838a"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b69f186179a030f517b1efeda262e1b462e34bce18362ccdfce9c22ee6204680"
      url "https://github.com/ottramst/gossm/releases/download/v#{version}/gossm_Linux_x86_64.tar.gz"
    end
  end

  name "gossm"
  desc "Interactive CLI for AWS SSM Session Manager"
  homepage "https://github.com/ottramst/gossm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gossm"]
    end
  end

  # No zap stanza required
end
